"""add user ownership to books

Revision ID: ba60395bdc82
Revises: 8d7f0c2a1b9e
Create Date: 2026-06-16 10:12:47.822632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba60395bdc82'
down_revision: Union[str, Sequence[str], None] = '8d7f0c2a1b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_books_isbn_uid'), table_name='books')
    op.create_index(op.f('ix_books_isbn_uid'), 'books', ['isbn_uid'], unique=False)
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_unique_constraint('uq_books_user_id_isbn_uid', 'books', ['user_id', 'isbn_uid'])
    op.create_foreign_key(
        'fk_books_user_id_profiles',
        'books',
        'profiles',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_user_id_profiles', 'books', type_='foreignkey')
    op.drop_constraint('uq_books_user_id_isbn_uid', 'books', type_='unique')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_index(op.f('ix_books_isbn_uid'), table_name='books')
    op.create_index(op.f('ix_books_isbn_uid'), 'books', ['isbn_uid'], unique=True)
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
